### ISSUE TITLE
@playlyfe/gql doesn't work with newer version of "graphql": "0.11.7",

### ISSUE THREAD

**Issue by albangiroux** [kumarharsh/graphql-for-vscode#97]
If the package.json use the latest version of graphql.js package, you have the following error:

[Info  - 10:42:06] NODE_PATH value is: xxxxxx
[Error - 10:42:08] Server initialization failed:
Request initialize failed with message: Cannot find module 'graphql/validation/rules/ArgumentsOfCorrectType'

Using "graphql": "0.11.7" fixed the problem...

**Comment by kumarharsh** [comment]
It should work with versions below 0.13. We are working on getting better support for all graphql versions soon.

**Comment by FredyC** [comment]
I've tried `@playlyfe/v3` which is supposed to work with `graphql@0.13`  but unfortunately there is this hard check in the plugin that effectively forbids it.

https://github.com/kumarharsh/graphql-for-vscode/blob/e52efb01732d46f6444bdcc577188e40cb6da5b8/src/server/server.ts#L68

Is there something I can help with on this? It's kinda surprising that with GraphQL being used more and more these super useful tools have lost interesting in maintaining them.

**Comment by FredyC** [comment]
@kumarharsh I would definitely like to help to get this moving. The extension helped me a lot before, but our backend guys decided to use `type Query extends Interface1 & Interface2 ...` it doesn't work anymore because older `graphql` module does not understand these. 

I guess the first step would be to figure out to use that compatible branch and have it loaded in the VSCode, shouldn't be that hard hopefully.

**Comment by FredyC** [comment]
Ok, guys, I want to thank for all the hard work and the joy this extension has brought in the past 👏 It's time to move on with the awesome [Apollo GraphQL](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo) that has emerged. It works out of the box without any complicated configuration and extra packages. I really recommend you to try it out.

**Comment by levrik** [comment]
@FredyC Sadly it doesn't support referencing a local schema consisting out of several files which I really need.

**Comment by FredyC** [comment]
@levrik Then file the suggestion. Apollo is surely a more active community and there are good chances for that to happen.
